### ISSUE TITLE
hide OTP messages

### ISSUE THREAD

**Issue by ScDor** [ScDor/alspam#117]
either hide all _(because come on, they're boring, 99% never spam and just annoy on the manual report screen)_ or allow unhiding with a mechanism similar to #60 

this may solve some of the reasons for the opening of #109

**Comment by ScDor** [comment]
no reason to un-hide them, they shall never show.

**Comment by ScDor** [comment]
on a second thoght, and after seeing some false-positives (not-otp hidden as otp), let's add that toggle to settings

**Comment by yogev1978** [comment]
@ScDor Add option to unhide OTP messages in Settings, similar to existing option "Unhide political messages". See example - this one is hidden and cannot unhide. 

![image](https://user-images.githubusercontent.com/10349199/97109865-6819bc80-16de-11eb-8be9-0666d6d07de2.png)
