### ISSUE TITLE
new inbox items only shown upon rescan

### ISSUE THREAD

**Issue by yogev1978** [ScDor/alspam#118]
My reported SPAM message is not found in the list of group claims until I forced a rescan

מחכים לך מחב"ד..
סמסי לנו את המילה 'אור' ותקבלי בחינם תזכורת להדלקת נרות שבת.

סמס לנו את המילה 'כח' ותקבל בחינם תזכורת להנחת תפילין.

![IMG_20201017_195632_470.jpg](https://user-images.githubusercontent.com/10349199/96348643-faa0d700-10b2-11eb-99fa-8d2792408d47.jpg)

**Comment by ScDor** [comment]
Note to self: inbox only searches for new inbox items

**Comment by ScDor** [comment]
this should be fixed in 0.038, could you test it?

**Comment by yogev1978** [comment]
@ScDor I installed 0.039 over 0.036. All my reported messages got deleted, and nothing appears in Inbox. Should I report a few messages first or what?

**Comment by yogev1978** [comment]
@ScDor Correction: After I entered "Report SPAM" option for the first time since installing 0.039, Inbox started showing some messages. But I think that's not what you wanted me to test, right?

**Comment by ScDor** [comment]
let's do this: text yourself "*foobar123*", which I have just added to the
db as a group item.
if this shows up as a "new!" item in your inbox, we're done.
