### ISSUE TITLE
main screen logo&title

### ISSUE THREAD

**Issue by yogev1978** [ScDor/alspam#121]
The amuta logo is corrupt on main screen (should be the same as on About screen). 

The application name is now missing on the main screen - I suggest to add it in the top bar.

![Screenshot_20201018-010524_אל-ספאם.jpg](https://user-images.githubusercontent.com/10349199/96354316-1372b200-10de-11eb-83d2-01b8f7ed8a14.jpg)

**Comment by ScDor** [comment]
the logo is intentionally shown this way.
showing the app name in the bar above it will be funny and redundant, why show the same two words twice?

@roikohno can we remove the bar on this activity only? so it doesn't stay blank

**Comment by yogev1978** [comment]
@ScDor Can you explain why on the main screen, the logo is intentionally shown this way? If you meant to show the logo as a placeholder of the application name, then indeed you need to remove the top green bar, and move the logo to there.

**Comment by ScDor** [comment]
I agree, that's exactly what I asked Roi about in the previous comment
