### ISSUE TITLE
GUI problems in About screen

### ISSUE THREAD

**Issue by yogev1978** [ScDor/alspam#122]
GUI problems in About screen:

1. Topbar has the application name - it should have the screen name (אודות)
2. When clicking on email or GitHub link and cancelling the question whether to open Email/Browser, the link stays marked as selected, even though it's no longer selected
3. Add Al-Spam website URL: https://www.alspam.org/ - make this also clickable, clicking on it should open the website in browser (this one copied from bug #54 which was closed)

![Screenshot_20201018-012013_אל-ספאם.jpg](https://user-images.githubusercontent.com/10349199/96354549-82510a80-10e0-11eb-82d0-58a111c97c01.jpg)

**Comment by roikohno** [comment]
#2 seems like an issue with the interface android studio provides. fixed the rest
