### ISSUE TITLE
don't throw user to main menu after reporting

### ISSUE THREAD

**Issue by ScDor** [ScDor/alspam#127]
selecting messages and manually reporting throws user to main menu.
let's not do that

**Comment by yogev1978** [comment]
Doesn't work as intended

**Comment by ScDor** [comment]
Please elaborate. What's your intention and what happens?

**Comment by yogev1978** [comment]
The checked checkboxes stay checked, and the messages stay on the screen, after reporting. Which even allows reporting them 2 or more times.

![Screenshot_20201019-150713_אל-ספאם.jpg](https://user-images.githubusercontent.com/10349199/96449159-1fb15900-121d-11eb-9f0d-c4a904883b8c.jpg)

**Comment by yogev1978** [comment]
@BEAdi Now works correctly - great job! Thanks a lot.
