### ISSUE TITLE
reformat inbox detail screen

### ISSUE THREAD

**Issue by yogev1978** [ScDor/alspam#132]
GUI problems in "Group claim details" screen:
- [x] The screen header is not correct - it should be "תביעות משותפות" and not "אל-ספאם"
- [x] The title is not shown completely. Also please change the title to "מתארגנת תביעה קבוצתית"
- [x] The text size is too big to fit everything on one screen
- [x] Received message date and time is not presented.
- [x] Text of the SMS message itself should be bold or another font, to distinguish it from text of the application.

![image](https://user-images.githubusercontent.com/10349199/96615565-19e57180-130a-11eb-8ac4-d1fc967230f0.png)

**Comment by roikohno** [comment]
Changes title to simply "הודעות ופיצויים" to account for any sort of message.
Gui overflowing supposed to be fixed now (will push to master soon)

@ScDor Can you:
1. check if gui fixed on a device with messages in inbox?
2. fix the issues I haven't checked yet? Seems like they are serverside or require a db rewrite of inboxmessage class

**Comment by yogev1978** [comment]
@roikohno 

> Changes title to simply "הודעות ופיצויים" to account for any sort of message.

This is not good enough, as it's also the title of the previous screen. So this screen needs to have a different title.
Maybe "פרטי ההודעה/פיצוי" ?

**Comment by ScDor** [comment]
> Changes title to simply "הודעות ופיצויים" to account for any sort of message.
> Gui overflowing supposed to be fixed now (will push to master soon)
> 
> @ScDor Can you:
> 
> 1. check if gui fixed on a device with messages in inbox?
> 2. fix the issues I haven't checked yet? Seems like they are serverside or require a db rewrite of inboxmessage class

1. checked, works (after today's 2e4d3fee203f209df8d3a0ad8e8bc70b02100a7a, thanks for fixing it)
2. sure, let's take this offline

**Comment by ScDor** [comment]
closed in bdacaf5ba8da9568821c07bb8b8c8b4e4384c56d and finalized in d10eaa994dfd665cf8f67adc8362d2949227d76e
