### ISSUE TITLE
Manual Report to server

### ISSUE THREAD

**Issue by roikohno** [ScDor/alspam#3]
Add activity for manual report of sms (gui + functionalty):
- [x] Show list of all sms on screen (via smsreader.read()), with checkbox for each sms
- [x] when clicked "send", take all sms messages with checkbox clicked and send to server using dbwriter 
- [x] Maintain in local storage set of already-checked messages

**Comment by roikohno** [comment]
- [ ] Switch to RecycleView instead of outdated ListView
- [ ] Maintain list (in local storage) of already reported messages, and don't show them on screen.

**Comment by ScDor** [comment]
8caf2736fb72139735e0d11d1bf3e2fb4aff6163

**Comment by ScDor** [comment]
note: commit isn't related
