### ISSUE TITLE
Change the displayed date to display year in 4 digits

### ISSUE THREAD

**Issue by yogev1978** [ScDor/alspam#52]
Please change the displayed date to display year in 4 digits (like 03/10/2020 and not 03/10/20).
Right now the year is displayed in 2 digits, this makes it harder to read the date quickly.
![image](https://user-images.githubusercontent.com/10349199/95389800-07783a80-08fd-11eb-929e-68c9971b5c36.png)

**Comment by ScDor** [comment]
on a Samsung GalaxyS9, the date bar breaks, so 01/02/2020 
it shows as 
```
 01/02/202
         0
```

**Comment by yogev1978** [comment]
Also on Samsung Galaxy S8

![image](https://user-images.githubusercontent.com/10349199/95504508-803acd80-09b5-11eb-973f-f5c0efaca228.png)
