### ISSUE TITLE
Display SMS received time in each SMS (in 24-hour format)

### ISSUE THREAD

**Issue by yogev1978** [ScDor/alspam#53]
Display SMS received time in each SMS (in 24-hour format)
Display the time both in "Received SMS messages" list and in "Reported messages" list.

**Comment by roikohno** [comment]
Is this really needed? We're not an SMS client (...yet) and it will only clutter each cardview.

**Comment by yogev1978** [comment]
@roikohno SMS received time is mandatory for all SPAM claims on SMS messages. Sometimes you also receive 2 or more SPAM SMS messages from the same sender name on the same day, so showing just the date is not enough. Place the time on the same row as SMSC server number, and it won't take an extra line.

**Comment by roikohno** [comment]
Ok, that makes sense. Will do.
