### ISSUE TITLE
Rejecting application permissions shows just a black screen, and not the screen that it used showing before.

### ISSUE THREAD

**Issue by yogev1978** [ScDor/alspam#67]
Rejecting application permissions shows just a black screen, and not the screen that it used showing before.

Now:
![Screenshot_20201011-013205_אל-ספאם.jpg](https://user-images.githubusercontent.com/10349199/95666381-9c7b6d80-0b61-11eb-9236-640becf2b8a6.jpg)

Before:
![Screenshot_20201008-220439_אל-ספאם.jpg](https://user-images.githubusercontent.com/10349199/95666388-b74de200-0b61-11eb-8c1b-d3f1ccc090fa.jpg)

**Comment by ScDor** [comment]
duplicate to #5, thanks for the screenshots
