### ISSUE TITLE
Add an option to show reported date and time on "My Reports" screen

### ISSUE THREAD

**Issue by yogev1978** [ScDor/alspam#68]
On "My Reports" screen, add an option to show date and time when the message was reported to the server.

**Comment by ScDor** [comment]
how would this benefit a user?

**Comment by yogev1978** [comment]
> how would this benefit a user?

This will help the user understand why he/she missed a group claim, or why he/she doesn't get any class action messages. It will also encourage more reporting I think. In addition, it will make possible sorting the reported messages by date reported, and not only by date received. I agree that it's a low priority issue, though.

**Comment by roikohno** [comment]
group claims have nothing to do with report date,  this just confuses the user. It might encourage reporting, though. Will get around to this later, not critical now and requires tweaking the local DB.

**Comment by ScDor** [comment]
I disagree. There's absolutely no connection between the day user A reported a message and the occasion something shows on their screen.
@yogev1978, note that we only show current, relevant, available groups to join (or ways to claim compensation as result of a class act). "missed" groups/class act results **are not shown** at all.

**Comment by yogev1978** [comment]
@ScDor What about encouraging reporting SPAM and allowing to sort this list by reported date, in addition to received date?

**Comment by ScDor** [comment]
Got it. I'd say it's a low priority but perhaps, because it changes local db fields, we better do it soon, at least add the fields (even if not showing them to user)
