### ISSUE TITLE
merge manualreport and reported activity

### ISSUE THREAD

**Issue by ScDor** [ScDor/alspam#74]
make a single, tab view of messages with an option to see "my reported messages" rather than have a separate screen, possibly using tabs to move (similar to the tabs we have in inbox)

**Comment by roikohno** [comment]
This is not a smart decision. They are separate activities with separate functions. Can we close this issue?

**Comment by ScDor** [comment]
the idea was using tabview or some checkbox to move between reported/not reported, but now it doesn't seem like a big or too relevant issue, and the activities are relatively different so let's close this one (for now?)
