### ISSUE TITLE
lengthen toast times

### ISSUE THREAD

**Issue by ScDor** [ScDor/alspam#82]
for some users, the [shortening of toast times](https://github.com/ScDor/alspam/commit/94eea7bd1e3d70b847e2572fa9f23b83d8a1f5d1) makes it hard to read as they disappear quickly

**Comment by yogev1978** [comment]
@ScDor Need to lengthen at least the long messages, for example this one
![image](https://user-images.githubusercontent.com/10349199/95868577-0a4ab380-0d73-11eb-9ced-542286d80d21.png)
