### ISSUE TITLE
filter messages when reading

### ISSUE THREAD

**Issue by ScDor** [ScDor/alspam#9]
have DBWriter ignore specific senders, to prevent unnecessary updates and junk
consider using "not in" when querying native SMS DB

- [x] set a list of ignored senders
- [x] ignore them when reading SMS
- [x] read denylist of senders from server

**Comment by MikeMerz** [comment]
How do I decide which sender is spam?
Is it implemented or by my implemention?

**Comment by ScDor** [comment]
start with some function that gets the phone contacts, then use
constructQuery to filter those contacts out (so we don't get messages from
contacts)

**Comment by MikeMerz** [comment]
Does the user can choose the contacts which will be uploaded or it uploads them all automatically?

**Comment by ScDor** [comment]
contacts are never uploaded, but filtered locally on the device.

**Comment by ScDor** [comment]
should read exactSenders for filtering from server

**Comment by ScDor** [comment]
now happens on denyList
