### ISSUE TITLE
Not all political messages are hidden

### ISSUE THREAD

**Issue by yogev1978** [ScDor/alspam#98]
Not all political messages are hidden when I choose an option to hide political messages from settings. See attached screenshot with example of political message that still appears.
![20201016_130938.jpg](https://user-images.githubusercontent.com/10349199/96246399-3eabb300-0fb1-11eb-92fb-c36179e8d14b.jpg)

**Comment by ScDor** [comment]
hiding **all** political messages and **only** them appeared to be not trivial. @BEAdi checked it (based on reported messages, their ranks, and the ratio between the political rank to others) and decided on some threshold, preferring false-negatives (such as the one in your screenshot) on false-positives (hiding non-political messages with words like בחירות, that appeared to be more common than expected).

**Comment by yogev1978** [comment]
@ScDor Makes sense. Closing as "won't fix".
